micronaut:
  application:
    name: keymgr

datasources:
  default:
    url: ${JPA_URI:`jdbc:h2:mem:devDb`}
    driverClassName: ${JPA_DRIVER:`org.h2.Driver`}
    username: ${JPA_USER:`sa`}
    password: ${JPA_PASS:``}
    dialect: ${JPA_DIALECT:`H2`}

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        bytecode:
          provider: none

grpc:
  server:
    keep-alive-time: 3h
    max-inbound-message-size: 1024

external:
  uri:
    itau: ${ITAU_URI:`http://localhost:9091`}
    bcb: ${BCB_URI:`http://localhost:8082`}